# Generated by Django 4.2.7 on 2025-09-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
