# Generated by Django 4.2.7 on 2025-09-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_remove_product_tags_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='calc.tag'),
        ),
    ]
